SWShop/Areas/Admin/Controllers/ProductController.cs
using SWShop.DataAccess.Data;
using SWShop.DataAccess.Repository.IRepository;
using SWShop.Models;
using SWShop.Models.ViewModels;
using SWShop.Ultility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data;
using System.Drawing.Printing;
using System.Security.Claims;

namespace SWShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            var objProduct = _unitOfWork.Product.GetAll(includeProperties: "Category").ToList();

            return View(objProduct);
        }
        public IActionResult Upsert(int? id)
        {
            ProductVM productVM = new()
            {
                CategoryList = _unitOfWork.Category.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
                Product = new Product()
            };
            if (id == null || id == 0)
            {
                return View(productVM);
            }
            else
            {
                productVM.Product = _unitOfWork.Product.Get(u => u.Id == id, includeProperties: "ProductImages");
                return View(productVM);
            }

        }
        [HttpPost]
        public IActionResult Upsert(ProductVM productVM, List<IFormFile> files)
        {
            if (ModelState.IsValid)
            {
                if (productVM.Product.Id == 0)
                {
                    _unitOfWork.Product.Add(productVM.Product);
                }
                else
                {
                    _unitOfWork.Product.Update(productVM.Product);
                }

                _unitOfWork.Save();

                string wwwRootPath = _webHostEnvironment.WebRootPath;
                if (files != null)
                {
                    foreach (IFormFile file in files)
                    {
                        string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                        string productPath = @"images\products\product-" + productVM.Product.Id;
                        string finalPath = Path.Combine(wwwRootPath, productPath);

                        if (!Directory.Exists(finalPath))
                        {
                            Directory.CreateDirectory(finalPath);
                        }

                        using (var fileStream = new FileStream(Path.Combine(finalPath, fileName), FileMode.Create))
                        {
                            file.CopyTo(fileStream);
                        }

                        ProductImage productImage = new()
                        {
                            ImageUrl = @"\" + productPath + @"\" + fileName,
                            ProductId = productVM.Product.Id,
                        };

                        if (productVM.Product.ProductImages == null)
                        {
                            productVM.Product.ProductImages = new List<ProductImage>();
                        }
                        productVM.Product.ProductImages.Add(productImage);
                    }
                    _unitOfWork.Product.Update(productVM.Product);
                    _unitOfWork.Save();
                }


                TempData["success"] = "Product created/updated successfully!";
                return RedirectToAction("Index");
            }
            else
            {
                productVM.CategoryList = _unitOfWork.Category.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                });
                return View(productVM);
            }
        }

        public IActionResult DeleteImage(int imageId)
        {
            var imageToBeDeleted = _unitOfWork.ProductImage.Get(u => u.Id == imageId);
            int productId = imageToBeDeleted.ProductId;
            if (imageToBeDeleted != null)
            {
                if (!string.IsNullOrEmpty(imageToBeDeleted.ImageUrl))
                {
                    var oldImagePath =
                                        Path.Combine(_webHostEnvironment.WebRootPath,
                                        imageToBeDeleted.ImageUrl.TrimStart('\\'));

                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }

                _unitOfWork.ProductImage.Remove(imageToBeDeleted);
                _unitOfWork.Save();

                TempData["success"] = "Deleted successfully";
            }
            return RedirectToAction(nameof(Upsert), new {id= productId });
        }

        [HttpPost]
        public IActionResult AddSizeAmount(int productId, string sizeName, int amount)
        {
            if (!string.IsNullOrEmpty(sizeName))
            {
                var size = new Size
                {
                    ProductId = productId,
                    Name = sizeName,
                    Amount = amount
                };

                Size sizeFromDb = _unitOfWork.Size.Get(u => u.Name == sizeName && u.ProductId == productId);

                if (sizeFromDb != null)
                {
                    sizeFromDb.Amount += amount;
                    _unitOfWork.Size.Update(sizeFromDb);
                    _unitOfWork.Save();
                }
                else
                {
                    _unitOfWork.Size.Add(size);
                    _unitOfWork.Save();
                }
                TempData["success"] = "Size update successfully";

                return Ok();
            }
            else
            {
                return Ok();
            }
        }

        public IActionResult ProductSize(int productId)
        {
            var objSize = _unitOfWork.Size.GetAll(u=>u.ProductId.Equals(productId)).ToList();
            return View(objSize);
        }
        public IActionResult ProductSizeEdit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Size sizeFromDb = _unitOfWork.Size.Get(c => c.Id == id);
            if (sizeFromDb == null)
            {
                return NotFound();
            }
            return View(sizeFromDb);
        }
        [HttpPost]
        public IActionResult ProductSizeEdit(Size obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Size.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Edit size successfully!";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult ProductSizeDelete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Size sizeFromDb = _unitOfWork.Size.Get(c => c.Id == id);
            if (sizeFromDb == null)
            {
                return NotFound();
            }
            return View(sizeFromDb);
        }
        [HttpPost, ActionName("ProductSizeDelete")]
        public IActionResult ProductSizeDeletePOST(int? id)
        {
            Size? obj = _unitOfWork.Size.Get(c => c.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            _unitOfWork.Size.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "Delete size successfully!";
            return RedirectToAction("Index");
        }

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            List<Product> objProductList = _unitOfWork.Product.GetAll(includeProperties: "Category").ToList();
            foreach (var product in objProductList)
            {
                product.QuantitySold = _unitOfWork.OrderDetail.GetAll(includeProperties: "OrderHeader")
                                .Where(od => od.ProductId == product.Id && od.OrderHeader.OrderStatus != SD.StatusPending && od.OrderHeader.PaymentStatus != SD.PaymentStatusPending)
                                .Sum(od => od.Count);

                product.QuantityRemain = _unitOfWork.Size.GetAll().Where(u=>u.ProductId == product.Id).Sum(x=>x.Amount);
                product.Sizes = null;
            }
            return Json(new { data = objProductList });
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var productToBeDeleted = _unitOfWork.Product.Get(u => u.Id == id);
            if (productToBeDeleted == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            //var oldImagePath = 
            //                    Path.Combine(_webHostEnvironment.WebRootPath,
            //                    productToBeDeleted.ImageUrl.TrimStart('\\'));

            //if (System.IO.File.Exists(oldImagePath))
            //{
            //    System.IO.File.Delete(oldImagePath);
            //}

            string productPath = @"images\products\product-" + id;
            string finalPath = Path.Combine(_webHostEnvironment.WebRootPath, productPath);

            if (Directory.Exists(finalPath))
            {
                string[] filePaths = Directory.GetFiles(finalPath);
                foreach (string filePath in filePaths)
                {
                    System.IO.File.Delete(filePath);

SWShop/Areas/Customer/Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SWShop.DataAccess.Data;
using SWShop.DataAccess.Repository;
using SWShop.DataAccess.Repository.IRepository;
using SWShop.Models;
using SWShop.Models.ViewModels;
using SWShop.Ultility;
using System.Security.Claims;

namespace SWShop.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class ShopController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public ShopController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IActionResult> Index(int? category, string searchTerm = null, int pageNumber = 1, int pageSize = 9,  decimal? minPrice = null, decimal? maxPrice = null, string? size = null)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            if (claimsIdentity.IsAuthenticated)
            {
                var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
                HttpContext.Session.SetInt32(SD.SessionCart,
                        _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == userId).Count());
            }
            var products = await _unitOfWork.Product.GetProductsAsync(searchTerm, pageNumber, pageSize, category, minPrice, maxPrice, size, includeProperties: "ProductImages,Likes,Sizes");
            foreach (var product in products)
            {
                product.QuantityRemain = product.Sizes.Sum(x => x.Amount);
                var rates = _unitOfWork.Rate.GetAll(u => u.ProductId == product.Id);
                int star = 0;
                if (rates.Count() > 0)
                {
                    star = (int)Math.Ceiling(rates.Average(r => r.Star));
                    product.Star = star;
                }
                if (claimsIdentity.IsAuthenticated)
                {
                    var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
                    if (product.Likes.Where(l => l.ApplicationUserId == userId && l.IsLike).Count() > 0)
                    {
                        product.IsLike = true;
                    }
                }

            }
            var totalCount = await _unitOfWork.Product.GetProductsCountAsync(searchTerm, pageNumber, pageSize, category, minPrice, maxPrice, size);

            ViewData["SearchTerm"] = searchTerm;
            ViewData["PageNumber"] = pageNumber;
            ViewData["PageSize"] = pageSize;
            ViewData["TotalCount"] = totalCount;
            ViewData["Category"] = category;
            ViewData["Size"] = size;
            ViewData["MinPrice"] = minPrice;
            ViewData["MaxPrice"] = maxPrice;

            // Calculate pagination values
            var totalPages = (int)Math.Ceiling((double)totalCount / pageSize);
            var hasPreviousPage = pageNumber > 1;
            var hasNextPage = pageNumber < totalPages;

            // Set pagination values in ViewBag
            ViewBag.TotalPages = totalPages;
            ViewBag.HasPreviousPage = hasPreviousPage;
            ViewBag.HasNextPage = hasNextPage;
            ViewBag.PreviousPageNumber = hasPreviousPage ? pageNumber - 1 : 1;
            ViewBag.NextPageNumber = hasNextPage ? pageNumber + 1 : totalPages;

            HomeVM homeVM = new()
            {
                CategoryList = _unitOfWork.Category.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
                SizeList = _unitOfWork.Size.GetAll().Select(s => s.Name).Distinct().ToList(),
                MinPrice = (int)_unitOfWork.Product.GetAll().Min(s => s.Price),
                MaxPrice = (int)_unitOfWork.Product.GetAll().Max(s => s.Price),
                ProductList = products
            };

            return View(homeVM);
        }

        public IActionResult Likes()
        {
            IEnumerable<Product> productList = new List<Product>();
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            if (claimsIdentity.IsAuthenticated)
            {
                var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
                HttpContext.Session.SetInt32(SD.SessionCart,
                        _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == userId).Count());
                HttpContext.Session.SetInt32(SD.SessionLike,
                        _unitOfWork.Like.GetAll(u => u.ApplicationUserId == userId && u.IsLike == true).Count());

                productList = _unitOfWork.Like.GetAll(includeProperties: "Product,Product.Sizes,Product.ProductImages").Where(u => u.ApplicationUserId == userId && u.IsLike == true)
                                                    .Select(l => l.Product)
                                                    .ToList();

                foreach (var product in productList)
                {
                    product.QuantityRemain = product.Sizes.Sum(x => x.Amount);
                    var rates = _unitOfWork.Rate.GetAll(u => u.ProductId == product.Id);
                    int star = 0;
                    if (rates.Count() > 0)
                    {
                        star = (int)Math.Ceiling(rates.Average(r => r.Star));
                        product.Star = star;
                    }
                    if (claimsIdentity.IsAuthenticated)
                    {
                        userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
                        if (product.Likes.Where(l => l.ApplicationUserId == userId && l.IsLike).Count() > 0)
                        {
                            product.IsLike = true;
                        }
                    }

                }
            }

            return View(productList);
        }
    }
}

SWShop/Areas/Customer/Views/Shop/Likes.cshtml
@model IEnumerable<Product>


<!-- Breadcrumb Begin -->
<div class="breadcrumb-option">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb__links">
                    <a asp-area="Customer" asp-controller="Home" asp-action="Index"><i class="fa fa-home"></i> Home</a>
                    <span>Likes</span>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->
<!-- Shop Section Begin -->

<section class="shop spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-3">
                
            </div>
            <div class="col-lg-9 col-md-9">
                <div class="row">
                    @foreach (var product in Model)
                    {
                        <div class="col-lg-4 col-md-6">
                            <div class="product__item @(product.SalePrice != 0?"sale":"") ">
                                @if (product.ProductImages != null && product.ProductImages.Count() > 0)
                                {
                                    <div class="product__item__pic set-bg" data-setbg="@product.ProductImages.FirstOrDefault().ImageUrl.Replace("\\", "/")">
                                        @if (product.QuantityRemain == 0)
                                        {
                                            <div class="label stockout" style="background: #111111;">hết hàng</div>
                                        }
                                        else if ((DateTime.Now - product.CreatedDate).Days < 7)
                                        {
                                            <div class="label new" style="background: #36a300;">Mới</div>
                                        }
                                        else if (product.SalePrice != 0)
                                        {
                                            <div class="label sale">Sale</div>
                                        }
                                        <ul class="product__hover">
                                            <li><a href="@product.ProductImages.FirstOrDefault().ImageUrl.Replace("\\", "/")" class="image-popup"><span class="arrow_expand"></span></a></li>
                                            <li class="liLike" data-productId="@product.Id" data-isLike="@(!product.IsLike)">
                                                <a href="#">
                                                    @if (product.IsLike)
                                                    {
                                                        <span class="icon_heart"></span>
                                                    }
                                                    else
                                                    {
                                                        <span class="icon_heart_alt"></span>
                                                    }
                                                </a>
                                            </li>
                                            <li>
                                                <a asp-controller="Home" asp-action="Details"
                                           asp-route-productId="@product.Id"><span class="icon_bag_alt"></span></a>
                                            </li>
                                        </ul>
                                    </div>
                                }
                                else
                                {
                                    <div class="product__item__pic set-bg" data-setbg="https://placehold.co/500x600/png">
                                        @if (product.QuantityRemain == 0)
                                        {
                                            <div class="label stockout" style="background: #111111;">hết hàng</div>
                                        }
                                        else if ((DateTime.Now - product.CreatedDate).Days < 7)
                                        {
                                            <div class="label new" style="background: #36a300;">Mới</div>
                                        }
                                        else if (product.SalePrice != 0)
                                        {
                                            <div class="label sale">Sale</div>
                                        }
                                        <ul class="product__hover">
                                            <li><a href="https://placehold.co/500x600/png" class="image-popup"><span class="arrow_expand"></span></a></li>
                                            <li class="liLike" data-productId="@product.Id" data-isLike="@(!product.IsLike)">
                                                <a href="#">
                                                    @if (product.IsLike)
                                                    {
                                                        <span class="icon_heart"></span>
                                                    }
                                                    else
                                                    {
                                                        <span class="icon_heart_alt"></span>
                                                    }
                                                </a>
                                            </li>
                                            <li>
                                                <a asp-controller="Home" asp-action="Details"
                                           asp-route-productId="@product.Id"><span class="icon_bag_alt"></span></a>
                                            </li>
                                        </ul>
                                    </div>
                                }

                                <div class="product__item__text">
                                    <h6>
                                        <a asp-controller="Home" asp-action="Details"
                                       asp-route-productId="@product.Id">@product.Name</a>
                                    </h6>
                                    <div class="rating">
                                        @for (int i = 0; i < 5; i++)
                                        {
                                            if (i < product.Star)
                                            {
                                                <i class="fa fa-star"></i>
                                            }
                                            else
                                            {
                                                <i class="fa fa-star-o"></i>
                                            }
                                        }
                                    </div>
                                    @if (@product.SalePrice == 0)
                                    {
                                        <div class="product__price">@product.Price.ToString("C0", new System.Globalization.CultureInfo("vi-VN")).Replace(" ", "")</div>
                                    }
                                    else
                                    {
                                        <div class="product__price">@product.SalePrice.ToString("C0", new System.Globalization.CultureInfo("vi-VN")).Replace(" ", "") <span>$ @product.Price.ToString("C0", new System.Globalization.CultureInfo("vi-VN")).Replace(" ", "")</span></div>
                                    }
                                </div>
                            </div>
                        </div>
                    }

                    <div class="col-lg-12 text-center">
                        @if (ViewBag.TotalPages > 1)
                        {
                            <div class="pagination__option">
                                @if (ViewBag.HasPreviousPage)
                                {
                                    <a href="@Url.Action("Index", "Shop", new { searchTerm = ViewData["SearchTerm"], pageNumber = ViewBag.PreviousPageNumber, pageSize = ViewData["PageSize"] })"><i class="fa fa-angle-left"></i></a>
                                }
                                @for (int i = 1; i <= ViewBag.TotalPages; i++)
                                {
                                    <a href="@Url.Action("Index", "Shop", new { searchTerm = ViewData["SearchTerm"], pageNumber = i, pageSize = ViewData["PageSize"] })" class="@((int)ViewData["PageNumber"] == i ? "bg-dark text-white" : "")">@i</a>
                                }
                                @if (ViewBag.HasNextPage)
                                {
                                    <a href="@Url.Action("Index", "Shop", new { searchTerm = ViewData["SearchTerm"], pageNumber = ViewBag.NextPageNumber, pageSize = ViewData["PageSize"] })"><i class="fa fa-angle-right"></i></a>
                                }
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>
<!-- Shop Section End -->
@section scripts{
    <script>
        $(function () {
            $('.table').DataTable({
                paging: false,
                searching: false,
                info: false
            });
        });
    </script>
    <script>
        $(document).ready(function () {

            $('.liLike').click(function () {
                debugger;
                var productId = $(this).data('productid');
                var isLike = $(this).data('islike');
                $.ajax({
                    type: "POST",
                    url: "/Customer/Home/Like",
                    data: {
                        productId: productId,
                        isLike: isLike
                    },
                    success: function (data) {
                        console.log("Like updated successfully.");
                        location.reload();
                    },
                    error: function (xhr, status, error) {
                        console.log("An error occurred while updating the like.");
                    }
                });
            });
        });
    </script>
}

SWShop/Areas/Customer/Views/Shop/Shop.cshtml
@model List<Product>

<form action="@Url.Action("Index", "Product")" method="get">
    <div class="form-group">
        <label for="searchTerm">Search:</label>
        <input type="text" name="searchTerm" value="@ViewData["SearchTerm"]" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Search</button>
</form>



<table class="table">
    <thead>
        <tr>